import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

import java.nio.charset.StandardCharsets

plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.4.0'
    id("com.gradleup.shadow") version "9.5.1"

    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
//    id("xyz.jpenilla.run-paper") version "3.0.2"
//    id("xyz.jpenilla.resource-factory-bukkit-convention") version "1.3.1"
}

group 'io.seekankan.github'
version '2.0-SNAPSHOT'

//def paperweightDevelopmentBundle = configurations.create("paperweightDevelopmentBundle")
def javaVersion = 25

//paperweight
//paperweight {
//    reobfArtifactConfiguration = io.papermc.paperweight.userdev.ReobfArtifactConfiguration.MOJANG_PRODUCTION
//    javaLauncher = javaToolchains.launcherFor {
//        languageVersion = JavaLanguageVersion.of(21)
//    }
//}
paperweight {
    javaLauncher = javaToolchains.launcherFor {
        // Example scenario:
        // Paper 1.17.1 was originally built with JDK 16 and the bundle
        // has not been updated to work with 21+ (but we want to compile with a 25 toolchain)
        languageVersion = JavaLanguageVersion.of(24)
    }
}

build {
    dependsOn(shadowJar)
}
shadowJar {
//    relocate("de.tr7zw.changeme.nbtapi", "io.seekankan.github.kansky.nbtapi")

    dependencies {
//        exclude(dependency('com.github.shynixn.kspigot:.*'))
//        exclude(dependency('org.spigotmc:.*'))
    }
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA'
    exclude '**/module-info.class'
    exclude 'META-INF/maven/**', 'META-INF/versions/**', 'META-INF/licenses/**'
    entryCompression = ZipEntryCompression.STORED
    zip64 = true

    relocate 'kotlin.reflect', 'io.seekankan.github.kanreattribute.shaded.kotlin.reflect'
//    reloacte 'kotlinx.coroutines', 'io.seekankan.github.kanreattribute.shaded.coroutines'
    relocate 'org.jetbrains.kotlinx', 'io.seekankan.github.kanreattribute.shaded.kotlinx'

    relocate 'io.seekankan.github.kanreattribute.compact', 'io.seekankan.github.kanreattribute.shaded.internal.compact'
    relocate 'org.koin', 'io.seekankan.github.kanreattribute.shaded.koin'
    relocate 'net.axay.kspigot', 'io.seekankan.github.kanreattribute.shaded.kspigot'

//    relocate '_COROUTINE', 'io.seekankan.github.kanreattribute.shaded._COROUTINE'
    relocate 'co.touchlab.stately', 'io.seekankan.github.kanreattribute.shaded.stately'
    relocate 'net.wesjd', 'io.seekankan.github.kanreattribute.shaded.wesjd'
    relocate 'org.intellij', 'io.seekankan.github.kanreattribute.shaded.intellij'
    relocate 'org.jetbrains', 'io.seekankan.github.kanreattribute.shaded.jetbrains'
    relocate 'com.fasterxml', 'io.seekankan.github.kanreattribute.shaded.com.fasterxml'


    //Adventure api
//    relocate 'net.kyori', 'io.seekankan.github.kanreattribute.shaded.kyori'

//    relocate 'io.papermc.lib', 'io.seekankan.github.kanreattribute.shaded.paperlib'

    def toShade = [
            'org.yaml.snakeyaml'
    ]
    toShade.forEach {
        relocate(it, "io.seekankan.github.kanreattribute.shaded.$it")
    }
    mergeServiceFiles()
}
tasks.register('copyPlugin', Copy) {
//    from file("${rootDir}/build/libs/kansky-1.0-SNAPSHOT-all.jar")
    from file("${rootDir}/build/libs/kanreattribute-" + version + "-all.jar")
    into file("${rootDir}/testserver/plugins")
}
tasks.register('copyPlugin1.21.11', Copy) {
    from file("${rootDir}/build/libs/kanreattribute-" + version + "-all.jar")
    into file("${rootDir}/testserver1.21.11/plugins")
}
tasks.register('copyPlugin26.1.2', Copy) {
    from file("${rootDir}/build/libs/kanreattribute-" + version + "-all.jar")
    into file("${rootDir}/testserver26.1.2/plugins")
}

repositories {
    maven { url 'https://maven.aliyun.com/repository/public' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://mvn.lumine.io/repository/maven-public/' }
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven { url 'https://papermc.io/repo/repository/maven-public/'}
    maven {
        name = "CodeMC"
        url = uri("https://repo.codemc.io/repository/maven-public/")
    }
    maven {
        url = 'https://repo.extendedclip.com/releases/'
    }
    maven { //kspigot
        url = 'https://jitpack.io'
    }
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }

    mavenCentral()
}

dependencies {
    implementation 'org.jetbrains:annotations:20.1.0'
    implementation 'org.jetbrains.kotlin:kotlin-reflect:2.2.20'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.0'
    implementation 'io.insert-koin:koin-core:4.2.1'

//    implementation project(':KanUtil')

//    compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
//    paperweightDevelopmentBundle "io.papermc.paper:dev-bundle:1.21.1-R0.1-SNAPSHOT"
//    paperweight.paperDevBundle("1.21.1-R0.1-SNAPSHOT.build.+")
//    paperweight.paperDevBundle("26.1.2.build.+")
    paperweight.paperDevBundle("26.1.2.build.+")

    compileOnly 'me.clip:placeholderapi:2.11.6'

    implementation 'net.axay:kspigot:1.16.29'


    //New Adventure API(MiniMessage)
//    def adventureVersion = "4.15.0"
//    implementation("net.kyori:adventure-text-minimessage:$adventureVersion")
    //AdventureAPI Platform
//    implementation("net.kyori:adventure-platform-bukkit:4.3.1") {
//    }
//    implementation("io.papermc:paperlib:1.0.8")

//    compileOnly fileTree(dir: 'lib/compileOnly', includes: ['*.jar'])
//    implementation fileTree(dir: 'lib/implementation', includes: ['*.jar'])

//    //json
    implementation("com.fasterxml.jackson.core:jackson-core:2.18.3")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.18.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.18.3")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.18.3") {
        exclude group: 'org.yaml', module: "snakeyaml"
    }
    implementation("com.fasterxml.jackson.module:jackson-module-parameter-names:2.18.3")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.18.3")

    //yaml
//    implementation("org.yaml:snakeyaml:2.6")
    implementation("org.yaml:snakeyaml:1.33")
//    implementation("org.yaml:snakeyaml:1.27")

    //nbt api
    compileOnly("de.tr7zw:item-nbt-api-plugin:2.15.7")

    //vault
    compileOnly("com.github.MilkBowl:VaultAPI:1.7") {
        exclude group: 'org.bukkit', module: "bukkit"
    }

    //test dependencies
    //junit
    platform('org.junit:junit-bom:5.14.4')
    implementation platform('org.junit:junit-bom:5.14.4')
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')

    //mock bukkit
//    testImplementation("com.github.seeseemelk:MockBukkit-v1.16:1.5.2")
//    testImplementation 'com.github.MockBukkit:MockBukkit:v26.1.2-SNAPSHOT'
//    testImplementation 'org.mockbukkit.mockbukkit:mockbukkit-v26.1.2:1.21-R0.1-SNAPSHOT'
//    testImplementation("org.mockbukkit.mockbukkit:mockbukkit-v26.1.2:4.114.0")
    testImplementation("org.mockbukkit.mockbukkit:mockbukkit-v1.21:4.110.0")

    //mockk

}

//test


//tasks.register('checkTestShadowJar') {
//    dependsOn tasks.named('shadowJarForTest')
//}



test {
    group = "verification"
    description = "Runs tests with shaded main classes."
//    dependsOn(shadowJarForTest)

    // Keep only test-specific runtime libs/classes, then add shaded main jar.
//    def testOnlyRuntime = sourceSets.test.runtimeClasspath - sourceSets.main.runtimeClasspath
//    classpath = testOnlyRuntime + files(tasks.named('shadowJarForTest').flatMap { it.archiveFile })

//    println(
//            classpath
//    )
//    classpath = files()
//    classpath = files(
//            tasks.shadowJarForTest.outputs.files.singleFile,
//            sourceSets.test.output.classesDirs,
//            sourceSets.test.output.resourcesDir,
//    )
//    classpath += sourceSets.test.runtimeClasspath

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
        showStandardStreams = true
    }

    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(javaVersion))
    }
//    sourceCompatibility = JavaVersion.VERSION_1_8
//    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks {
    compileJava {
        options.release = javaVersion
    }
    javadoc {
        options.encoding = StandardCharsets.UTF_8.name()
    }
}

//kotlin {
//    jvmToolchain(17)
//}
tasks.withType(KotlinCompile).configureEach {
    compilerOptions {
        freeCompilerArgs.addAll([
                "-Xjvm-default=all",
                "-java-parameters",
                "-Xemit-jvm-type-annotations"
        ])
        incremental = true
    }
}
tasks.withType(JavaCompile).configureEach() {
//    sourceCompatibility = jvmVersion
//    targetCompatibility = jvmVersion
    options.encoding = "UTF-8"
}
